apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-db-instance.cpjuy4xox6lb.eu-west-2.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-db-instance.cpjuy4xox6lb.eu-west-2.rds.amazonaws.com:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-db-instance.cpjuy4xox6lb.eu-west-2.rds.amazonaws.com:3306/userdb
  orderdb_url: mongodb+srv://admin:mdpmongo@atlas-cluster.ifh74l7.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

